name: macOS CI

env:
  LLVM_VER: 22

on:
  push:
  pull_request:

jobs:
  macos-universal-build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v6
      with:
        submodules: 'recursive'
        fetch-depth: 0

    - name: Install Vulkan SDK
      uses: jakoch/install-vulkan-sdk-action@v1
      with:
        optional_components: com.lunarg.vulkan.volk
        install_runtime: true
        cache: true
        stripdown: true

    - name: Install LLVM
      run: |
          brew install llvm@${{env.LLVM_VER}}

    - name: Build and pack Iris
      run: |
        git fetch --all --tags
        export PATH="/opt/homebrew/opt/llvm@${{env.LLVM_VER}}/bin:$PATH"
        export CPPFLAGS="-I/opt/homebrew/opt/llvm@${{env.LLVM_VER}}/include"
        export LDFLAGS="-L/opt/homebrew/opt/llvm@${{env.LLVM_VER}}/lib"
        cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=$(brew --prefix llvm@${{env.LLVM_VER}})/bin/clang -DCMAKE_CXX_COMPILER=$(brew --prefix llvm@${{env.LLVM_VER}})/bin/clang++
        cmake --build build
        sudo cmake --install build
        mkdir -p ./build/dist
        cp -R ./build/iris.app ./build/dist

    - uses: actions/upload-artifact@v7
      with:
        name: iris-latest-macos-universal
        path: ./build/dist
